export const labubuData = [
    {
        id: 1,
        name: "Time to Chill Labubu",
        image:
            "https://images.stockx.com/images/Pop-Mart-LABUBU-Time-to-Chill-Vinyl-Plush-Doll.jpg",
        priceUSD: 125,
        lore: "This Labubu is always relaxed, sipping iced tea under a palm tree.",
        stock: 3,
        rarity: "Epic",
        liveWatchers: 5,
        popularity: "Hot Pick",
    },
    {
        id: 2,
        name: "Fall in Wild Labubu",
        image:
            "https://images.stockx.com/images/Pop-Mart-The-Monsters-Fall-In-Wild-Vinyl-Plush-Doll.jpg",
        priceUSD: 135,
        lore: "A true jungle explorer with a wild heart and fearless attitude.",
        stock: 2,
        rarity: "Rare",
        liveWatchers: 8,
        popularity: "🔥 Trending",
    },
    {
        id: 3,
        name: "Jump for Joy Labubu",
        image:
            "https://images.novelship.com/product/pop_mart_labubu_the_monsters_jump_for_joy_vinyl_pl_0_50416.jpeg",
        priceUSD: 110,
        lore: "No one jumps higher than this cheerful little monster!",
        stock: 5,
        rarity: "Common",
        liveWatchers: 10,
        popularity: "Popular",
    },
    {
        id: 4,
        name: "Best of Luck Labubu",
        image:
            "https://d2cva83hdk3bwc.cloudfront.net/pop-mart-the-monsters-best-of-luck-vinyl-plush-doll-1.jpg",
        priceUSD: 120,
        lore: "Known for bringing good luck to collectors worldwide.",
        stock: 1,
        rarity: "Legendary",
        liveWatchers: 2,
        popularity: "Collector's Choice",
    },
    {
        id: 5,
        name: "Dress Be Latte Labubu",
        image:
            "https://d2cva83hdk3bwc.cloudfront.net/pop-mart-the-monsters-dress-be-latte-vinyl-plush-doll-1.jpg",
        priceUSD: 118,
        lore: "Stylish and cozy — always dressed for a warm latte vibe.",
        stock: 4,
        rarity: "Uncommon",
        liveWatchers: 6,
        popularity: "Fan Favorite",
    },
    {
        id: 6,
        name: "Mystery Box Labubu",
        image:
            "https://d5ibtax54de3q.cloudfront.net/eyJidWNrZXQiOiJraWNrYXZlbnVlLWFzc2V0cyIsImtleSI6InByb2R1Y3RzLzExMjg3OS81ZTY5YzQ4MjI5NDk5MWQ2N2I0YzQzMzkwYTg0YzE5NC5wbmciLCJlZGl0cyI6eyJyZXNpemUiOnsid2lkdGgiOjE0MDB9fX0=",
        priceUSD: 150,
        lore: "A surprise Labubu that could be any of the popular designs!",
        stock: 0,
        rarity: "Mystery",
        liveWatchers: 15,
        popularity: "Mystery Box",
    },
    {
        id: 7,
        name: "Dress Be Latte Labubu",
        image:
            "https://images.stockx.com/images/Pop-Mart-Labubu-The-Monsters-Jump-for-Joy-Vinyl-Plush-Doll.jpg",
        priceUSD: 115,
        lore: "A fashionable Labubu that loves to dress up for every occasion.",
        stock: 6,
        rarity: "Uncommon",
        liveWatchers: 4,
        popularity: "Trending",
    },
    {
        id: 8,
        name: "Lucky Charm Labubu",
        image:
            "https://i5.walmartimages.com/asr/5bc4d519-8d66-47a3-a6aa-42fa7c91951c.e4fc1ed3d1626b659e4d0e78af7c479f.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF",
        priceUSD: 130,
        lore: "This Labubu is said to bring good fortune to its owner.",
        stock: 2,
        rarity: "Rare",
        liveWatchers: 3,
        popularity: "Collector's Item",
    },
    {
        id: 9,
        name: "Adventure Awaits Labubu",
        image:
            "https://s.alicdn.com/@sc04/kf/H648796b7ab3a4fa483d96ceaa0681efdO.jpg_720x720q50.jpg",
        priceUSD: 140,
        lore: "Always ready for the next big adventure, this Labubu is a thrill-seeker.",
        stock: 3,
        rarity: "Epic",
        liveWatchers: 7,
        popularity: "Adventure Lover",
    },
    {
        id: 10,
        name: "Chill Vibes Labubu",
        image:
            "https://i5.walmartimages.com/asr/3a37375d-5a03-49dd-8f94-f6d83760338b.fcd1f490305e8961e422f2dae848f03b.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF",
        priceUSD: 125,
        lore: "This Labubu is all about relaxation and good vibes.",
        stock: 5,
        rarity: "Common",
        liveWatchers: 9,
        popularity: "Chill Pick",
    },
    {
        id: 11,
        name: "Lucky Star Labubu",
        image:
            "https://i5.walmartimages.com/asr/fcbc00a3-0115-449f-8b26-75f83aa7571b.a5811dc62d5c1768da14a87bc65ed1a4.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF",
        priceUSD: 145,
        lore: "A starry-eyed Labubu that brings luck and joy to its owner.",
        stock: 4,
        rarity: "Legendary",
        liveWatchers: 6,
        popularity: "Star Collector",
    },
    {
        id: 12,
        name: "Dreamy Labubu",
        image:
            "https://i5.walmartimages.com/asr/20b0e96b-1390-40bf-af6e-75e2e34c49b8.e8fb064534a6c540d616ca7ff11cdf4d.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF",
        priceUSD: 155,
        lore: "This Labubu is always dreaming of new adventures and fun.",
        stock: 3,
        rarity: "Epic",
        liveWatchers: 8,
        popularity: "Dreamer's Choice",
    },
    {
        id: 13,
        name: "Mystic Labubu",
        image:
            "https://cdn.shopify.com/s/files/1/0603/3031/1875/files/main-square_22145e98-82d8-4a77-bcaf-1bb05c947f42_540x.jpg?=75&v=1736322846",
        priceUSD: 160,
        lore: "A mystical Labubu that holds secrets of the universe.",
        stock: 2,
        rarity: "Rare",
        liveWatchers: 10,
        popularity: "Mystic Vibes",
    },
    {
        id: 14,
        name: "Sunny Day Labubu",
        image:
            "https://i5.walmartimages.com/asr/d3e0c29c-8f31-400c-812b-2479b48b0e85.ee8c81b9d96a814978f7e0ab7aa1a1fe.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF",
        priceUSD: 120,
        lore: "This Labubu loves sunny days and bright smiles.",
        stock: 5,
        rarity: "Common",
        liveWatchers: 12,
        popularity: "Sunny Favorite",
    },
    {
        id: 15,
        name: "Starry Night Labubu",
        image:
            "https://i5.walmartimages.com/asr/0ef3948c-98f4-4c81-8958-412c596351d9.0b4d95d3191fdbe3992a8f2171c06653.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF",
        priceUSD: 135,
        lore: "A dreamy Labubu that loves to gaze at the stars.",
        stock: 3,
        rarity: "Epic",
        liveWatchers: 11,
        popularity: "Star Gazer",
    },
    {
        id: 16,
        name: "Adventure Buddy Labubu",
        image:
            "https://i5.walmartimages.com/asr/3a882786-4f9e-4331-b368-44d5126f5bb0.b5a858cc0a50fb94a348b60072e8b74d.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF",
        priceUSD: 150,
        lore: "Your perfect companion for all adventures, big or small.",
        stock: 4,
        rarity: "Rare",
        liveWatchers: 9,
        popularity: "Adventure Seeker",
    },
];
